language: go

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x

addons:
  chrome: stable

script:
  # Diff Go format.
  - diff -u <(echo -n) <(gofmt -d .)
  # Run Go tests.
  - GOOS=js GOARCH=wasm go test -v -exec="$(go env GOROOT)/misc/wasm/go_js_wasm_exec"
